export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const LOAD_ADMIN_REQUEST = 'LOAD_ADMIN_REQUEST'
export const LOAD_ADMIN_SUCCESS = 'LOAD_ADMIN_SUCCESS'
export const LOAD_ADMIN_FAIL = 'LOAD_ADMIN_FAIL'
export const LOAD_STAFFS_REQUEST = 'LOAD_STAFFS_REQUEST'
export const LOAD_STAFFS_SUCCESS = 'LOAD_STAFFS_SUCCESS'
export const LOAD_STAFFS_FAIL = 'LOAD_STAFFS_DETAILS_FAIL'
export const LOAD_STAFFS_DETAILS_REQUEST = 'LOAD_STAFFS_DETAILS_REQUEST'
export const LOAD_STAFFS_DETAILS_SUCCESS = 'LOAD_STAFFS_DETAILS_SUCCESS'
export const LOAD_STAFFS_DETAILS_FAIL = 'LOAD_STAFFS_DETAILS_FAIL'
export const LOAD_STAFFS_DELETE_REQUEST = 'LOAD_STAFFS_DELETE_REQUEST'
export const LOAD_STAFFS_DELETE_SUCCESS = 'LOAD_STAFFS_DELETE_SUCCESS'
export const LOAD_STAFFS_DELETE_FAIL = 'LOAD_STAFFS_DELETE_FAIL'
export const ADD_STAFFS_REQUEST = 'ADD_STAFFS_REQUEST'
export const ADD_STAFFS_SUCCESS = 'ADD_STAFFS_SUCCESS'
export const ADD_STAFFS_FAIL = 'ADD_STAFFS_DETAILS_FAIL'
export const EDIT_STAFFS_REQUEST = 'EDIT_STAFFS_REQUEST'
export const EDIT_STAFFS_SUCCESS = 'EDIT_STAFFS_SUCCESS'
export const EDIT_STAFFS_FAIL = 'EDIT_STAFFS_DETAILS_FAIL'
export const LOAD_CLIENT_REQUEST = 'LOAD_CLIENT_REQUEST'
export const LOAD_CLIENT_SUCCESS = 'LOAD_CLIENT_SUCCESS'
export const LOAD_CLIENT_FAIL = 'LOAD_CLIENT_DETAILS_FAIL'
export const LOAD_CLIENT_DETAILS_REQUEST = 'LOAD_CLIENT_DETAILS_REQUEST'
export const LOAD_CLIENT_DETAILS_SUCCESS = 'LOAD_CLIENT_DETAILS_SUCCESS'
export const LOAD_CLIENT_DETAILS_FAIL = 'LOAD_CLIENT_DETAILS_FAIL'
export const LOAD_CLIENT_DELETE_REQUEST = 'LOAD_CLIENT_DELETE_REQUEST'
export const LOAD_CLIENT_DELETE_SUCCESS = 'LOAD_CLIENT_DELETE_SUCCESS'
export const LOAD_CLIENT_DELETE_FAIL = 'LOAD_CLIENT_DELETE_FAIL'
export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_DETAILS_FAIL'
export const EDIT_CLIENT_REQUEST = 'EDIT_CLIENT_REQUEST'
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS'
export const EDIT_CLIENT_FAIL = 'EDIT_CLIENT_DETAILS_FAIL'
export const LOAD_RATE_REQUEST = 'LOAD_RATE_REQUEST'
export const LOAD_RATE_SUCCESS = 'LOAD_RATE_SUCCESS'
export const LOAD_RATE_FAIL = 'LOAD_RATE_DETAILS_FAIL'
//event
export const LOAD_EVENT_REQUEST = 'LOAD_EVENT_REQUEST'
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS'
export const LOAD_EVENT_FAIL = 'LOAD_EVENT_FAIL'

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL'

export const LOAD_EVENT_DETAILS_REQUEST = 'LOAD_EVENT_DETAILS_REQUEST'
export const LOAD_EVENT_DETAILS_SUCCESS = 'LOAD_EVENT_DETAILS_SUCCESS'
export const LOAD_EVENT_DETAILS_FAIL = 'LOAD_EVENT_DETAILS_FAIL'

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST'
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS'
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL'


export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_FAIL = 'EDIT_EVENT_FAIL'

export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const UPDATE_ALL_FILTERS = 'UPDATE_ALL_FILTERS'
export const SELECT_EVENT = "SELECT_EVENT"


export const  UPDATE_ISADMINAPPROVAL_REQUEST = 'UPDATE_ISADMINAPPROVAL_REQUEST'
export const UPDATE_ISADMINAPPROVAL_SUCCESS = 'UPDATE_ISADMINAPPROVAL_SUCCESS'
export const UPDATE_ISADMINAPPROVAL_FAIL = ' UPDATE_ISADMINAPPROVAL_FAIL'


export const  UPDATE_ADMINSTATUS_REQUEST = 'UPDATE_ADMINSTATUS_REQUEST'
export const UPDATE_ADMINSTATUS_SUCCESS = 'UPDATE_ADMINSTATUS_SUCCESS'
export const UPDATE_ADMINSTATUS_FAIL = 'UPDATE_ADMINSTATUS_FAIL'

export const GET_COMPLETED_REQUEST = 'GET_COMPLETED_REQUEST'
export const  GET_COMPLETED_SUCCESS = 'GET_COMPLETED_SUCCESS'
export const  GET_COMPLETED_FAIL = 'GET_COMPLETED_FAIL'

//employee
export const LOAD_EMPLOYEE_REQUEST = 'LOAD_EMPLOEE_REQUEST'
export const LOAD_EMPLOYEE_SUCCESS = 'LOAD_EMPLOEE_SUCCESS'
export const LOAD_EMPLOYEE_FAIL = 'LOAD_EMPLOEE_FAIL'

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOEE_REQUEST'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOEE_SUCCESS'
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOEE_FAIL'

export const LOAD_EMPLOYEE_DETAILS_REQUEST = 'LOAD_EMPLOEE_DETAILS_REQUEST'
export const LOAD_EMPLOYEE_DETAILS_SUCCESS = 'LOAD_EMPLOEE_DETAILS_SUCCESS'
export const LOAD_EMPLOYEE_DETAILS_FAIL = 'LOAD_EMPLOEE_DETAILS_FAIL'

//staff rate
export const  ADD_STAFFRATE_REQUEST = 'ADD_STAFFRATE_REQUEST'
export const ADD_STAFFRATE_SUCCESS = 'ADD_STAFFRATE_SUCCESS '
export const ADD_STAFFRATE_FAIL = ' ADD_STAFFRATE_FAIL'

export const  GET_FILTER_REQUEST = 'GET_FILTER_REQUEST'
export const GET_FILTER_SUCCESS = 'GET_FILTER_SUCCESS '
export const GET_FILTER_FAIL = ' GET_FILTER_FAIL'

export const  GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST'
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS '
export const GET_INVOICE_FAIL = ' GET_INVOICE_FAIL'